version: '3.8'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: wait-for mysql:3306 -t 20 -- /usr/local/bin/docker-entrypoint.sh node index.js
    networks:
      - minharede
    volumes:
      - ./node:/home/node/app
    tty: true
    ports:
      - "3300:3300"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - minharede

networks:
  minharede:
    driver: bridge